# Generated by Django 5.1.3 on 2024-11-25 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperHeroes', '0003_rename_strength_hero_strengthsss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='location',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='strengthsss',
            new_name='strengths',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='weakness',
            new_name='weaknesses',
        ),
    ]
