# Generated by Django 5.1.3 on 2024-12-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperHeroes', '0005_rename_title_hero_superheroname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='music',
        ),
    ]
