# Generated by Django 5.1.3 on 2024-11-27 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperHeroes', '0005_alter_hero_reporter_delete_reporter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='location',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='weakness',
            new_name='weaknesses',
        ),
        migrations.AlterField(
            model_name='hero',
            name='reporter',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
