# Generated by Django 5.1.3 on 2024-12-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesphotos', '0002_alter_photo_image_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hero',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
