# Generated by Django 5.1.3 on 2024-12-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlesphotos', '0004_alter_article_photo_alter_photo_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bio',
            new_name='biography',
        ),
    ]
