# Generated by Django 5.1.3 on 2024-11-24 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperHeroes', '0002_rename_strength3_hero_age_rename_weakness2_hero_food_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='strength',
            new_name='strengthsss',
        ),
    ]
