# Generated by Django 5.1.3 on 2024-11-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperHeroes', '0004_rename_location_hero_residence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='title',
            new_name='SuperheroName',
        ),
    ]
