# Generated by Django 5.1.3 on 2024-12-04 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperHeroes', '0007_alter_hero_reporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='music',
            new_name='SuperheroName',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='strength',
            new_name='strengths',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='title',
        ),
    ]
